# Generated by Django 2.2.17 on 2021-04-04 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bakery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pafe',
            new_name='Page',
        ),
    ]
